/**
 * TLE loading utilities - local assets first, remote fallback
 */

export interface TLEData {
  catid: number;
  line1: string;
  line2: string;
  source: 'local' | 'celestrak';
}

const BASE_PATH = process.env.NODE_ENV === 'production' ? '/tle-fetcher' : '';

/**
 * Load TLE from local assets (generated by CI)
 */
async function loadLocalTLE(catid: number): Promise<TLEData | null> {
  try {
    const response = await fetch(`${BASE_PATH}/tle/${catid}.tle`);
    if (!response.ok) {
      return null;
    }
    
    const text = await response.text();
    const lines = text.trim().split('\n');
    
    // TLE can be 2 lines (no name) or 3 lines (with name)
    if (lines.length < 2) {
      console.warn(`Invalid TLE format for CATID ${catid}`);
      return null;
    }
    
    const line1 = lines.length === 3 ? lines[1] : lines[0];
    const line2 = lines.length === 3 ? lines[2] : lines[1];
    
    return {
      catid,
      line1,
      line2,
      source: 'local',
    };
  } catch (error) {
    console.warn(`Failed to load local TLE for ${catid}:`, error);
    return null;
  }
}

/**
 * Load TLE from CelesTrak as fallback
 */
async function loadCelestrakTLE(catid: number): Promise<TLEData | null> {
  try {
    const url = `https://celestrak.org/NORAD/elements/gp.php?CATNR=${catid}&FORMAT=TLE`;
    const response = await fetch(url);
    
    if (!response.ok) {
      return null;
    }
    
    const text = await response.text();
    const lines = text.trim().split('\n');
    
    if (lines.length < 2) {
      console.warn(`Invalid TLE format from CelesTrak for CATID ${catid}`);
      return null;
    }
    
    const line1 = lines.length === 3 ? lines[1] : lines[0];
    const line2 = lines.length === 3 ? lines[2] : lines[1];
    
    return {
      catid,
      line1,
      line2,
      source: 'celestrak',
    };
  } catch (error) {
    console.warn(`Failed to load CelesTrak TLE for ${catid}:`, error);
    return null;
  }
}

/**
 * Load TLE with fallback strategy
 */
export async function loadTLE(
  catid: number,
  source: 'local' | 'celestrak' | 'both' = 'both'
): Promise<TLEData | null> {
  if (source === 'local' || source === 'both') {
    const local = await loadLocalTLE(catid);
    if (local) {
      return local;
    }
    
    if (source === 'local') {
      return null;
    }
  }
  
  // Fallback to CelesTrak
  return loadCelestrakTLE(catid);
}

/**
 * Load multiple TLEs in parallel
 */
export async function loadTLEs(
  catids: number[],
  source: 'local' | 'celestrak' | 'both' = 'both'
): Promise<Map<number, TLEData>> {
  const promises = catids.map(catid => loadTLE(catid, source));
  const results = await Promise.all(promises);
  
  const tleMap = new Map<number, TLEData>();
  results.forEach((tle, index) => {
    if (tle) {
      tleMap.set(catids[index], tle);
    }
  });
  
  return tleMap;
}

/**
 * Get TLE URL for display/download
 */
export function getTLEUrl(catid: number, source: 'local' | 'celestrak'): string {
  if (source === 'local') {
    return `${BASE_PATH}/tle/${catid}.tle`;
  }
  return `https://celestrak.org/NORAD/elements/gp.php?CATNR=${catid}&FORMAT=TLE`;
}
