from datetime import datetime
from typing import Any

from .types import TLE

def parse(text: str, *, norad_id: str = ..., source: str = ...) -> TLE: ...
def checksum(line: str) -> bool: ...
def epoch(line1: str) -> datetime: ...
def sgp4(*args: Any, **kwargs: Any) -> Any: ...
