import { useState } from 'react';
import Head from 'next/head';
import ControlPanel, { type FormData } from '@/components/ControlPanel';
import ResultsTable from '@/components/ResultsTable';
import Gauges from '@/components/Gauges';
import { parseDateTime } from '@/lib/time';
import { loadTLEs, getTLEUrl } from '@/lib/tle';
import { computeMultiplePasses, type PassSummary } from '@/lib/passes';

// IDs from ids.txt - in production, this could be loaded from an API endpoint
const DEFAULT_CATIDS = [25544, 43013]; // ISS and TESS as defaults

export default function Home() {
  const [isComputing, setIsComputing] = useState(false);
  const [passes, setPasses] = useState<PassSummary[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [showHelp, setShowHelp] = useState(false);
  
  const handleCompute = async (formData: FormData) => {
    setIsComputing(true);
    setError(null);
    setPasses([]);
    
    try {
      // Parse date/time
      const startTime = parseDateTime({
        date: formData.date,
        time: formData.time,
        useUTC: formData.useUTC,
      });
      
      if (!startTime) {
        throw new Error('Invalid date/time');
      }
      
      // Load TLEs for default satellites
      console.log('Loading TLEs...');
      const tleMap = await loadTLEs(DEFAULT_CATIDS, formData.tleSource);
      
      if (tleMap.size === 0) {
        throw new Error('No TLE data available. Please check your connection or try a different source.');
      }
      
      console.log(`Loaded ${tleMap.size} TLEs`);
      
      // Compute passes
      const observer = {
        latitude: formData.latitude,
        longitude: formData.longitude,
        altitude: 0,
      };
      
      const computedPasses = computeMultiplePasses(
        tleMap,
        {
          observer,
          startTime,
          durationMinutes: formData.totMinutes,
          minElevationDeg: formData.minElevationDeg,
          timeStepSec: 10,
        },
        getTLEUrl
      );
      
      console.log(`Found ${computedPasses.length} passes`);
      setPasses(computedPasses);
      
    } catch (err) {
      console.error('Computation error:', err);
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setIsComputing(false);
    }
  };
  
  return (
    <>
      <Head>
        <title>TLE Pass Dashboard - Satellite Tracker</title>
        <meta name="description" content="Real-time satellite pass prediction and tracking dashboard" />
      </Head>
      
      <main className="min-h-screen p-4 md:p-8">
        <div className="max-w-7xl mx-auto">
          {/* Header */}
          <div className="text-center mb-8">
            <h1 className="text-5xl md:text-6xl font-black glow-text text-pink-400 mb-2" style={{ fontFamily: 'Orbitron, sans-serif' }}>
              TLE PASS DASHBOARD
            </h1>
            <p className="text-cyan-300 text-lg">
              Satellite Line-of-Sight Prediction System
            </p>
            <button
              onClick={() => setShowHelp(!showHelp)}
              className="mt-4 text-sm text-pink-400 hover:text-pink-300 underline"
            >
              {showHelp ? 'Hide Help' : 'Show Help'}
            </button>
          </div>
          
          {/* Help Section */}
          {showHelp && (
            <div className="panel mb-8">
              <h3 className="text-xl font-bold text-pink-400 mb-3">How It Works</h3>
              <div className="text-cyan-300 space-y-2 text-sm">
                <p>
                  This dashboard computes satellite passes (line-of-sight windows) for a given observer location and time period.
                </p>
                <p>
                  <strong className="text-pink-300">Line-of-Sight (LOS):</strong> A satellite is considered in LOS when its elevation angle above the horizon exceeds the minimum threshold (default 5°).
                </p>
                <p>
                  <strong className="text-pink-300">Time-on-Target (ToT):</strong> The duration window to search for passes, starting from the specified date/time.
                </p>
                <p>
                  <strong className="text-pink-300">Data Sources:</strong> TLE data comes from local assets (generated by CI) with fallback to CelesTrak. Metadata is fetched from SatNOGS DB and CelesTrak SATCAT APIs.
                </p>
                <p>
                  <strong className="text-pink-300">Algorithm:</strong> Uses SGP4 propagation (satellite.js) to compute satellite positions at 10-second intervals across the time window.
                </p>
              </div>
            </div>
          )}
          
          {/* Error Message */}
          {error && (
            <div className="panel mb-8 border-red-500">
              <p className="text-red-400 font-bold">⚠ ERROR</p>
              <p className="text-red-300 mt-2">{error}</p>
            </div>
          )}
          
          {/* Gauges */}
          <div className="mb-8">
            <Gauges passCount={passes.length} />
          </div>
          
          {/* Main Content Grid */}
          <div className="grid lg:grid-cols-3 gap-8">
            {/* Control Panel */}
            <div className="lg:col-span-1">
              <ControlPanel onSubmit={handleCompute} isComputing={isComputing} />
            </div>
            
            {/* Results */}
            <div className="lg:col-span-2">
              <ResultsTable passes={passes} />
            </div>
          </div>
          
          {/* Footer */}
          <footer className="mt-12 text-center text-cyan-300/50 text-sm">
            <p>
              TLE Fetcher Project | Data: CelesTrak, SatNOGS DB | 
              <a 
                href="https://github.com/cywf/tle-fetcher" 
                target="_blank" 
                rel="noopener noreferrer"
                className="ml-1 text-pink-400 hover:text-pink-300 underline"
              >
                GitHub
              </a>
            </p>
          </footer>
        </div>
      </main>
    </>
  );
}
