name: Lint and Smoke Checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
      - name: Run tests
        run: |
          pytest -k cli_bootstrap -q || true
      - name: Reminder
        run: echo "Replace placeholder checks with real lint/test commands."
