name: Build release wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    if: ${{ hashFiles('Cargo.toml') != '' }}
    runs-on: ubuntu-latest
    env:
      MATURIN_LOG_LEVEL: info
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements-dev.txt

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-

      - name: Install maturin
        run: |
          python -m pip install --upgrade pip
          python -m pip install maturin

      - name: Build wheels
        run: |
          set -Eeuo pipefail
          maturin build --release --out dist --interpreter python3.11

      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: maturin-wheels
          path: dist

      - name: Publish GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
